"""empty message

Revision ID: 4224bceeb26a
Revises: 
Create Date: 2017-02-03 12:55:33.226512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4224bceeb26a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_listings', sa.Column('list_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_listings', 'list_price')
    # ### end Alembic commands ###
